import Layout from "../src/components/Layout";
import getAppCommonData from "../src/inc/data/appCommonData";
import getHomeCommonData from "../src/inc/data/homepageData";
import AboutField from "../src/components/aboutField";
import Head from "next/head";

const about = ({appCommonData, homepageData}) => {


  const AcustomData = homepageData.data.aboutpage.aboutpages; 

  const titleData = homepageData.data.aboutpage.seo; 
  


    return (
    
      <>

          <Head>
          
          <title>{titleData.title}</title>
        <meta name="description" content="Generated by create next app..." />
        <link rel="icon" href="/favicon.ico" />



          </Head>


     <Layout appCommonData = {appCommonData}>
         <AboutField AcustomData={AcustomData} />
     </Layout>
     </>
        
    
    
    );
    
    
    };



    export async function getStaticProps() {
        return {
          props: {
            appCommonData: await getAppCommonData(),
            homepageData: await getHomeCommonData()
          }
        }
      }


    
    export default about;